### ISSUE TITLE
Reference to old script still on current live CD

### ISSUE THREAD

**Issue by sidkshatriya** [chimera-linux/chimera-install-scripts#1]
In https://github.com/chimera-linux/chimera-install-scripts/commit/a8ecaa8630e2592ea58822b725270431142ead85 there was a change made that replaced message that referred to "chimera-live-chroot" with "chimera-chroot".

I recently used `chimera-linux-aarch64-LIVE-20230915-base.iso` for an install and the the `chimera-bootstrap` script in it *still* says:

> "You can use chimera-live-chroot to get a shell in the system ..."

This caused a bit a confusion for me when I was installing the system.

Why is the `/usr/bin/chimera-bootstrap` script in above ISO still referring to the outdated script `chimera-live-chroot` ?

**Comment by JamiKettunen** [comment]
Should be fixed with https://github.com/chimera-linux/cports/commit/e5145773a418fad18ed7ab84106ebdcee916e3cc once fresh ISOs are made
